### PR TITLE
Fix: allow (re)setting the current catalog

### LINKED ISSUE #211: Allow setting the current catalog to cluster's name
The driver should not err if the application is trying to set the current catalog to the same value it returned, when queried for the current catalog.

### PR DESCRIPTION
**Pull request by bpintea**
This PR allows the application set the value of the current catalog attribute, in case this value is the same with what the driver had previously returned for this attribute.

Although Elasticsearch/SQL has no proper catalog support currently, this case should be supported as a safe use of the API.

This currently only works if the attribute had been retrieved before setting, on the same connection; specifically, it won't work when this would be set as a pre-connection attribute.

Closes #211.

### CODE REVIEW

File: test/test_driverconnect.cc [hunk 1]
```diff
@@ -7,6 +7,11 @@
 #include <gtest/gtest.h>
 #include "connected_dbc.h"
 
+/*  */
```
Comment (droberts195) [inline test/test_driverconnect.cc]: nit: empty comment

Comment (bpintea) [reply test/test_driverconnect.cc]: thanks, fixed.
