### PR TITLE
Fix: SQLGetData: only update offset if C-string data copied out

### LINKED ISSUE #220: SQLGetData: allow subsequent call past an initial one with 0 buffer space
Some apps will invoke `SQLGetData()` with zero buffer space, in an attempt to find out the length of the text/binary data, before (possibly allocating space for and) fetching it. Currently, the driver always advances on the available data, making the second call fail with "no data available".

### PR DESCRIPTION
**Pull request by bpintea**
This PR fixes a defect manifesting when getting C-strings with
SQLGetData, in two steps: a first invocation with a 0-space buffer, to
fetch the length of data available, then a subsequent one, with
appropriate buffer size, to actually fetch the data.

The second call would so far fail with "no data available anymore",
since the offset of so-far-read-data was incorrectly updated, also in
the case when no data was actually copied. This commit fixes it, only
updating the offset if there's space in output buffer to copy.

Fetching wide-strings works correctly.

Fixes #220.

### CODE REVIEW

File: driver/convert.c [hunk 1]
```diff
@@ -1472,37 +1475,37 @@ static SQLRETURN wstr_to_cstr(esodbc_rec_st *arec, esodbc_rec_st *irec,
...
+			for (c = (int)xstr.w.cnt + 1; 0 < c; c --) {
+				out_bytes = U16WC_TO_MBU8(xstr.w.str, c, charp, in_bytes);
+				if (0 < out_bytes) {
+					break; /* conversion succeeded */
+				} // else: out_bytes <= 0
+				if (! WAPI_ERR_EBUFF()) {
+					ERRNH(stmt, "failed to convert wchar_t* to char* for "
+						"string `" LWPDL "`.", c, xstr.w.str);
+					RET_HDIAGS(stmt, SQL_STATE_22018);
+				} // else: buffer too small for full string: trimm further
```
Comment (droberts195) [inline driver/convert.c]: typo: trimm -> trim

File: driver/convert.c [hunk 2]
```diff
@@ -1472,37 +1475,37 @@ static SQLRETURN wstr_to_cstr(esodbc_rec_st *arec, esodbc_rec_st *irec,
...
-			state = SQL_STATE_01004; /* indicate truncation */
-			c --; /* last char was overwritten with 0 -> dec xfed count */
-		}
-
-		/* only update offset if data is copied out */
-		gd_offset_update(stmt, xstr.w.cnt, c);
+			assert(0 < out_bytes);
+			if (charp[out_bytes - 1] != '\0') {
+				/* ran out of buffer => not 0-term'd and truncated already */
+				charp[out_bytes - 1] = 0;
```
Comment (droberts195) [inline driver/convert.c]: nit: in the test you used `'\0'` but on this line you're using `0`.  It shouldn't make any difference but might be nice to consistently use one or the other.

Comment (bpintea) [reply driver/convert.c]: Thanks, fixed them.
